/*
 * Micro-genre scene data for the world map.
 * Each entry represents a geographic music scene with real coordinates.
 * Names are canonical strings used for matching against Claude analysis results.
 */

export interface SceneEntry {
  name: string;
  region: string;
  lat: number;
  lng: number;
  radius: number;
  color: string;
  category: "Electronic" | "Indie" | "Urban" | "Experimental" | "Pop-adjacent";
  emerging: boolean;
  description: string;
  artists: string[];
}

export const SCENE_ENTRIES: SceneEntry[] = [
  {
    name: "UK Garage",
    region: "London, UK",
    lat: 51.5,
    lng: -0.1,
    radius: 14,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: false,
    description: "Skippy two-step rhythms and chopped vocal samples born from London's rave culture. The backbone of the UK's underground dance scene since the mid-90s.",
    artists: ["MJ Cole", "El-B", "Conducta"],
  },
  {
    name: "Grime",
    region: "London, UK",
    lat: 51.52,
    lng: -0.05,
    radius: 16,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Aggressive, rapid-fire MCing over dark, glitchy electronic beats. East London's definitive contribution to global rap culture.",
    artists: ["Skepta", "Wiley", "Stormzy"],
  },
  {
    name: "Baile Funk",
    region: "Rio de Janeiro, Brazil",
    lat: -22.9,
    lng: -43.2,
    radius: 13,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "High-energy favela bass music with call-and-response vocals and Miami bass-influenced beats. The sound of Rio's street parties.",
    artists: ["MC Kevinho", "Anitta", "DJ Rennan da Penha"],
  },
  {
    name: "Hyperpop",
    region: "Los Angeles, US",
    lat: 34.0,
    lng: -118.2,
    radius: 15,
    color: "#7F77DD",
    category: "Experimental",
    emerging: false,
    description: "Maximalist, digitally distorted pop that pushes Auto-Tune and synths to their breaking point. Genre-fluid and internet-native.",
    artists: ["100 gecs", "Charli XCX", "A.G. Cook"],
  },
  {
    name: "Footwork",
    region: "Chicago, US",
    lat: 41.8,
    lng: -87.6,
    radius: 12,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: false,
    description: "Ultra-fast 160 BPM tracks built for competitive dance battles on Chicago's South Side. Chopped samples and syncopated rhythms.",
    artists: ["DJ Rashad", "RP Boo", "DJ Spinn"],
  },
  {
    name: "Shoegaze Revival",
    region: "Manchester, UK",
    lat: 53.5,
    lng: -2.2,
    radius: 11,
    color: "#1D9E75",
    category: "Indie",
    emerging: false,
    description: "Walls of distorted guitar wash over dreamy vocals. A revival of the early-90s sound with modern production sensibilities.",
    artists: ["Nothing", "DIIV", "Ringo Deathstarr"],
  },
  {
    name: "Amapiano",
    region: "Johannesburg, South Africa",
    lat: -26.2,
    lng: 28.0,
    radius: 14,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: true,
    description: "Lush piano melodies, log drum basslines, and shuffling percussion from South Africa's townships. Now conquering global dancefloors.",
    artists: ["Kabza De Small", "DJ Maphorisa", "Uncle Waffles"],
  },
  {
    name: "City Pop Revival",
    region: "Tokyo, Japan",
    lat: 35.7,
    lng: 139.7,
    radius: 13,
    color: "#D4537E",
    category: "Pop-adjacent",
    emerging: false,
    description: "The glossy, funk-tinged Japanese pop of the 80s rediscovered by a global internet audience. Smooth synths and neon nostalgia.",
    artists: ["Tatsuro Yamashita", "Mariya Takeuchi", "Miki Matsubara"],
  },
  {
    name: "Midwest Emo",
    region: "Chicago, US",
    lat: 41.85,
    lng: -87.65,
    radius: 10,
    color: "#1D9E75",
    category: "Indie",
    emerging: false,
    description: "Twinkly guitars, confessional lyrics, and math-rock time signatures. The emotionally honest sound of suburban America.",
    artists: ["American Football", "Mom Jeans", "Tiny Moving Parts"],
  },
  {
    name: "UK Drill",
    region: "London, UK",
    lat: 51.48,
    lng: -0.12,
    radius: 14,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Dark, sliding 808s and aggressive flows adapted from Chicago drill but with a distinctly British cadence and slang.",
    artists: ["Central Cee", "Headie One", "Digga D"],
  },
  {
    name: "Afrobeats",
    region: "Lagos, Nigeria",
    lat: 6.5,
    lng: 3.4,
    radius: 16,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Infectious rhythms blending West African percussion with dancehall, hip-hop, and R&B. Lagos's gift to global pop.",
    artists: ["Burna Boy", "Wizkid", "Tems"],
  },
  {
    name: "Flamenco Nuevo",
    region: "Seville, Spain",
    lat: 37.4,
    lng: -5.9,
    radius: 10,
    color: "#7F77DD",
    category: "Experimental",
    emerging: true,
    description: "Traditional flamenco guitar and cante fused with electronic production and jazz harmony. Ancient passion meets modern experimentation.",
    artists: ["Rosalia", "Niño de Elche", "Rocio Marquez"],
  },
  {
    name: "Cumbia Digital",
    region: "Buenos Aires, Argentina",
    lat: -34.6,
    lng: -58.4,
    radius: 11,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: true,
    description: "Colombian cumbia rhythms remixed through laptop producers and bass-heavy sound systems. South America's digital folk music.",
    artists: ["Chancha Via Circuito", "Nicola Cruz", "El Remolón"],
  },
  {
    name: "Bedroom Pop",
    region: "Brooklyn, US",
    lat: 40.69,
    lng: -73.95,
    radius: 12,
    color: "#1D9E75",
    category: "Indie",
    emerging: false,
    description: "Lo-fi, intimate songwriting recorded in home studios. Soft vocals over hazy guitar and drum machine beats.",
    artists: ["Clairo", "Boy Pablo", "Men I Trust"],
  },
  {
    name: "Phonk",
    region: "Memphis, US",
    lat: 35.1,
    lng: -90.0,
    radius: 12,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Dark, lo-fi hip-hop sampling Memphis rap tapes from the 90s. Cowbell-heavy, distorted, and dripping with Southern gothic menace.",
    artists: ["DJ Smokey", "Soudiere", "Freddie Dredd"],
  },
  {
    name: "Vaporwave",
    region: "Seattle, US",
    lat: 47.6,
    lng: -122.3,
    radius: 11,
    color: "#7F77DD",
    category: "Experimental",
    emerging: false,
    description: "Slowed-down 80s pop and smooth jazz samples drenched in reverb and nostalgia. An internet art movement turned micro-genre.",
    artists: ["Macintosh Plus", "Saint Pepsi", "George Clanton"],
  },
  {
    name: "French House",
    region: "Paris, France",
    lat: 48.85,
    lng: 2.35,
    radius: 13,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: false,
    description: "Filtered disco loops, phaser-drenched funk, and four-on-the-floor grooves. Paris's answer to Chicago house.",
    artists: ["Daft Punk", "Justice", "Cassius"],
  },
  {
    name: "Bossa Nova Eletrônica",
    region: "São Paulo, Brazil",
    lat: -23.5,
    lng: -46.6,
    radius: 10,
    color: "#D4537E",
    category: "Pop-adjacent",
    emerging: true,
    description: "Classic bossa nova melodies and rhythms reimagined with electronic textures and ambient production. Digital tropicalia.",
    artists: ["Céu", "Tropkillaz", "Tim Bernardes"],
  },
  {
    name: "K-Indie",
    region: "Seoul, South Korea",
    lat: 37.6,
    lng: 127.0,
    radius: 12,
    color: "#1D9E75",
    category: "Indie",
    emerging: true,
    description: "South Korea's independent music scene — dream pop, post-punk, and folk outside the K-pop machine. Intimate and genre-diverse.",
    artists: ["Hyukoh", "The Black Skirts", "SE SO NEON"],
  },
  {
    name: "Melbourne Bounce",
    region: "Melbourne, Australia",
    lat: -37.8,
    lng: 144.9,
    radius: 11,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: false,
    description: "High-energy electro house with bouncy basslines and pitched-up vocal chops. Australia's festival-ready dancefloor weapon.",
    artists: ["Will Sparks", "Timmy Trumpet", "Joel Fletcher"],
  },
  {
    name: "Synthwave",
    region: "Miami, US",
    lat: 25.8,
    lng: -80.2,
    radius: 12,
    color: "#7F77DD",
    category: "Experimental",
    emerging: false,
    description: "Retro-futuristic synths channeling 80s action movie soundtracks and neon-lit car chases. Nostalgia as a sonic aesthetic.",
    artists: ["Kavinsky", "Perturbator", "Carpenter Brut"],
  },
  {
    name: "Afro-House",
    region: "Cape Town, South Africa",
    lat: -33.9,
    lng: 18.4,
    radius: 11,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: true,
    description: "Deep house rhythms infused with African percussion and spiritual vocal chants. Cape Town's contribution to the global house continuum.",
    artists: ["Black Coffee", "Shimza", "Culoe De Song"],
  },
  {
    name: "Emo Rap",
    region: "Atlanta, US",
    lat: 33.75,
    lng: -84.4,
    radius: 12,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Trap beats meet confessional, emotionally raw vocals with punk and emo influences. SoundCloud's most impactful crossover.",
    artists: ["Juice WRLD", "Lil Peep", "XXXTentacion"],
  },
  {
    name: "Lo-fi Hip-Hop",
    region: "New York, US",
    lat: 40.73,
    lng: -74.0,
    radius: 14,
    color: "#1D9E75",
    category: "Indie",
    emerging: false,
    description: "Mellow, sample-based beats with vinyl crackle and jazz piano loops. The internet's study music turned cultural phenomenon.",
    artists: ["Nujabes", "J Dilla", "Idealism"],
  },
  {
    name: "Reggaeton",
    region: "San Juan, Puerto Rico",
    lat: 18.47,
    lng: -66.1,
    radius: 16,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Dembow rhythms and Spanish-language vocals dominating global pop charts. Puerto Rico's most successful musical export.",
    artists: ["Bad Bunny", "Daddy Yankee", "J Balvin"],
  },
  {
    name: "Trap",
    region: "Atlanta, US",
    lat: 33.78,
    lng: -84.38,
    radius: 16,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "808 drum machines, hi-hat rolls, and dark synth pads from Atlanta's Zone 6. The dominant sound of modern hip-hop.",
    artists: ["Future", "Young Thug", "21 Savage"],
  },
  {
    name: "Techno",
    region: "Berlin, Germany",
    lat: 52.52,
    lng: 13.4,
    radius: 15,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: false,
    description: "Relentless four-on-the-floor kicks, industrial textures, and hypnotic repetition. Berlin's club scene is the global epicenter.",
    artists: ["Ben Klock", "Marcel Dettmann", "Nina Kraviz"],
  },
  {
    name: "Dembow",
    region: "Santo Domingo, DR",
    lat: 18.48,
    lng: -69.93,
    radius: 11,
    color: "#D85A30",
    category: "Urban",
    emerging: true,
    description: "Raw, percussion-heavy street music from the Dominican Republic. Driving rhythms that fuel reggaeton and beyond.",
    artists: ["El Alfa", "Rochy RD", "Tokischa"],
  },
  {
    name: "Dancehall",
    region: "Kingston, Jamaica",
    lat: 18.0,
    lng: -76.8,
    radius: 13,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Digital riddims and toasting vocals from Jamaica's sound system culture. The rhythmic DNA behind countless global genres.",
    artists: ["Vybz Kartel", "Popcaan", "Shenseea"],
  },
  {
    name: "Kuduro",
    region: "Luanda, Angola",
    lat: -8.84,
    lng: 13.23,
    radius: 10,
    color: "#3B8BD4",
    category: "Electronic",
    emerging: true,
    description: "Frenetic, uptempo electronic dance music from Angola's musseques. Aggressive beats meet acrobatic dance moves.",
    artists: ["Buraka Som Sistema", "DJ Marfox", "Puto Prata"],
  },
  {
    name: "Math Rock",
    region: "Osaka, Japan",
    lat: 34.7,
    lng: 135.5,
    radius: 10,
    color: "#7F77DD",
    category: "Experimental",
    emerging: false,
    description: "Complex time signatures, intricate guitar tapping, and technical precision. Japan's scene rivals the Midwest as the genre's spiritual home.",
    artists: ["toe", "LITE", "tricot"],
  },
  {
    name: "Drill (Chicago)",
    region: "Chicago, US",
    lat: 41.83,
    lng: -87.62,
    radius: 13,
    color: "#D85A30",
    category: "Urban",
    emerging: false,
    description: "Dark, nihilistic trap variant born from Chicago's South Side. Heavy 808s, violent lyrics, and raw street narratives.",
    artists: ["Chief Keef", "Lil Durk", "G Herbo"],
  },
  {
    name: "K-Pop",
    region: "Seoul, South Korea",
    lat: 37.55,
    lng: 126.97,
    radius: 16,
    color: "#D4537E",
    category: "Pop-adjacent",
    emerging: false,
    description: "Meticulously produced, visually stunning pop from South Korea's entertainment industry. A global cultural force.",
    artists: ["BTS", "BLACKPINK", "NewJeans"],
  },
  {
    name: "Nordic Folk",
    region: "Reykjavik, Iceland",
    lat: 64.15,
    lng: -21.95,
    radius: 9,
    color: "#1D9E75",
    category: "Indie",
    emerging: true,
    description: "Sparse, atmospheric folk drawing from Nordic landscapes and mythology. Haunting vocals and minimalist instrumentation.",
    artists: ["Sigur Rós", "Ólafur Arnalds", "Wardruna"],
  },
];
